1: Import the numpy package under the name np

In [1]:
import numpy as np

2:Create a null vector of size 10

In [2]:
x=np.zeros(10)


3:Create a vector with values ranging from 10 to 49

In [3]:
arr=np.arange(10,50)


4:Find the shape of previous array in question 3

In [4]:
arr.shape

(40,)

5:Print the type of the previous array in question 3

In [5]:
print(arr.dtype)

int64


6:Print the numpy version and the configuration

In [6]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/zebraking/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/zebraking/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/zebraking/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/zebraking/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/zebraking/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/zebraking/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/zebraking/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/zebraking/anaconda3/include']


7:Print the dimension of the array in question 3

In [7]:
print(arr.ndim)

1


8:Create a boolean array with all the True values

In [8]:
bol_arr=np.ones(10,dtype=bool)

9:Create a two dimensional array

In [9]:
x=np.array([[2,4,6],[6,8,4]])

10:Create a three dimensional array

In [10]:
x=np.arange(36).reshape(4,3,3)

11:Reverse a vector (first element becomes last)

In [11]:
a=np.arange(1,10)
a[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1])

12:Create a null vector of size 10 but the fifth value which is 1

In [12]:
x=np.zeros(10)
x[4]=1

13:Create a 3x3 identity matrix

In [13]:
x=np.eye(3)


14:arr = np.array([1, 2, 3, 4, 5])
Convert the data type of the given array from int to float

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

15:arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
Multiply arr1 with arr2

In [15]:
arr1 = np.array([[1., 2., 3.],

        [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],

       [7., 2., 12.]])
x=arr1 * arr2


arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],

        [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

        [7., 2., 12.]])
comparision=arr1 == arr2

Extract all odd numbers from arr with values(0-9)

In [17]:
x=np.arange(0,9)
x[x % 2==1]

array([1, 3, 5, 7])

Replace all odd numbers to -1 from previous array

In [18]:
x[x % 2==1]=-1

arr = np.arange(10)
Replace the values of indexes 5,6,7 and 8 to 12

In [19]:
arr=np.arange(10)
arr[5:9]=12

Create a 2d array with 1 on the border and 0 inside

In [20]:
arr=np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

        [4, 5, 6], 

        [7, 8, 9]])
arr2d[1,1]=12


arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64

Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
x=np.arange(0,9).reshape(3,3)
a=x[0]

Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
z=np.arange(0,9).reshape(3,3)

z[1,1]

4

Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
c=np.arange(0,9).reshape(3,3)
c[:2,2]

array([2, 5])

Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.017998076355793202 0.9987222211729783


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
find common elements in a and b

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


In [29]:
np.intersect1d(a,b)

array([2, 4])

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the positions where elements of a and b match

In [32]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)


(array([1, 3, 5, 7]),)

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will and Joe

In [85]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 

np.where(names!=['Will'])

(array([0, 1, 3, 5, 6]),)


Difficulty Level Hard

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [44]:

s=np.arange(1,16).reshape(5,3)
np.around(s,decimals=1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [89]:
x=np.arange(1,17).reshape(2,2,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

Swap axes of the array you created in Question 32

In [91]:
np.swapaxes(x,0,1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [96]:
x=np.random.rand(10)
x[x > 0.5]=0
x

array([0.        , 0.00452644, 0.34532104, 0.18671736, 0.        ,
       0.48078914, 0.        , 0.        , 0.28365552, 0.09469116])

Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [102]:
x=np.random.randn(12)
y=np.random.randn(12)

x1=np.max(x)
y1=np.max(y)

x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
Find the dot product of the above two matrix

In [49]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
From array a remove all items present in array b

In [52]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9]) 

result = np.setdiff1d(a, b)
print(result)


[1 2 3 4]


Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [70]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:,2]=newColumn
sampleArray


array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!

In [69]:
x=np.unique(names)
np.sort(x)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

Generate a matrix of 20 random values and find its cumulative sum

In [104]:
x=np.random.randn(20)
np.cumsum(x)

array([ 0.02199439, -0.28504423, -2.12994291, -1.1658675 , -2.62167698,
       -2.27431428, -1.12604119, -1.4026945 , -1.89997722, -0.08316679,
        0.61007551,  2.11714406,  2.07053636,  4.66397939,  4.62572273,
        3.41889301,  2.28893703,  2.02013739,  0.20201603,  1.72271443])