In [1]:
import numpy as np

# 1: Convert a 1D array to a 2D array with 2 rows?

In [3]:
arr=np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#  2:How to stack two arrays vertically?

In [7]:
arr1=np.array([2,5,8,1,6])
arr2=np.array([8,0,1,7,9])
np.vstack((arr1,arr2))

array([[2, 5, 8, 1, 6],
       [8, 0, 1, 7, 9]])

# 3: How to stack two arrays horizontally?

In [8]:
arr1=np.array([2,5,8,1,6])
arr2=np.array([8,0,1,7,9])
np.hstack((arr1,arr2))


array([2, 5, 8, 1, 6, 8, 0, 1, 7, 9])

# 4: How to convert an array of arrays into a flat 1d array?

In [12]:
a=np.array([[2,4,7],[9,1,3],[8,5,2]])
a.flatten()

array([2, 4, 7, 9, 1, 3, 8, 5, 2])

# 5: How to Convert higher dimension into one dimension?

In [16]:
a=np.array([[2,4,7],[9,1,3],[8,5,2]])
#to convert higher dimension into low we can use flatten and ravel function
a.ravel()

array([2, 4, 7, 9, 1, 3, 8, 5, 2])

# 6: Convert one dimension to higher dimension?

In [20]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 7: Create 5x5 an array and find the square of an array?

In [30]:
arr=np.arange(25).reshape(5,5)
np.square(arr)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

# 8:Create 5x6 an array and find the mean?

In [32]:
arr1=np.arange(30).reshape(5,6)
np.mean(arr1)

14.5

# 9:Find the standard deviation of the previous array in Q8?

In [33]:
np.std(arr1)

8.65544144839919

# 10:Find the median of the previous array in Q8?

In [34]:
np.median(arr1)

14.5

# 11:Find the transpose of the previous array in Q8?

In [36]:
arr1.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

# 12: Create a 4x4 an array and find the sum of diagonal elements?

In [43]:
arr2=np.arange(16).reshape(4,4)

np.diagonal(arr2).sum()

30

# 13: Find the determinant of the previous array in Q12?

In [45]:
np.linalg.det(arr2)

-2.9582283945787796e-30

# 14: Find the 5th and 95th percentile of an array?

In [46]:
print(np.percentile(arr,5))
print(np.percentile(arr,50))

1.2000000000000002
12.0


# 15:How to find if a given array has any null values?

In [52]:
arr=np.array([3,np.nan,7,8,np.nan])
np.isnan(arr)
#to check ho many values is null
np.isnan(arr).sum()

2